spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/lojaonline}
    username: ${SPRING_DATASOURCE_USERNAME:lojaonline}
    password: ${SPRING_DATASOURCE_PASSWORD:lojaonline}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
