version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: lojaonline
      POSTGRES_USER: lojaonline
      POSTGRES_PASSWORD: lojaonline
      TZ: America/Manaus
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lojaonline -d lojaonline"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - vestebem_network

  api:
    build: .
    container_name: vestebem_api
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lojaonline
      SPRING_DATASOURCE_USERNAME: lojaonline
      SPRING_DATASOURCE_PASSWORD: lojaonline
      TZ: America/Manaus
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - vestebem_network

volumes:
  postgres_data:

networks:
  vestebem_network:
spring.config.import=optional:file:.env[.properties],optional:file:./.env[.properties],optional:file:./backend/.env[.properties]
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
  
spring.jackson.time-zone=GMT-4
  
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=GMT-4
  
spring.devtools.restart.additional-paths=src/main/java
spring.devtools.restart.exclude=static/**,templates/**,**/*.txt

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true